### ISSUE TITLE
Multiple id array in Monitoring\MonitoringKeyword, method: getData()

### ISSUE THREAD

**Issue by Niekuba** [semstorm/semstorm-php-sdk#1]
Hello,

First of all, thank you for sharing this API.

I'm struggling with getData() method in Monitoring/MonitoringKeyword.php. I am successfully receiving correct response while providing single keyword id, however, unable to get data for multiple id's at the same time.

**What works:**
$kw = new MonitoringKeyword()
$data = [];
//"12345" is my keyword id
$data['id'] = 12345;

print_r($kw ->getData( $data ));

**What doesn't work:**
$kw = new MonitoringKeyword();
$data = [];
//"12345" and "123456" are my keyword ids
$data['id'] = array(12345, 123456);

print_r($kw ->getData( $data ));

Could you please provide correct (accepted by server) format of data['id'] for an array of id's?

Best regards,
Jakub

**Comment by semstorm** [comment]
Hello,
sorry for keeping you waiting. We just realeased version 3 API with many fixes and improvements and featuring some minor changes.
For your case working code will now look like that:
```
$instance = new MonitoringKeyword();
$params = array();
$params['id'] = array(461552, 461553);
$res = $instance->getDetails($params);
print_r( $res );
```
For detailed documentation see this section of [API Documentation](http://api.semstorm.com/?api=monitoring#keyword-get-details). We hope you will it helpful.

Best regards,
SEMSTORM team
